//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FCamacho_EvoPoint.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Permiso
    {
        public int Id { get; set; }
        public string Nombre_Empleado { get; set; }
        public string Apellidos_Empleado { get; set; }
        public int Tipo_Permiso { get; set; }
        public System.DateTime Fecha_Permiso { get; set; }
    
        public virtual TipoPermiso TipoPermiso { get; set; }
    }
}
